name: Build and test

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build typescript
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - name: Install npm packages
      run: npm install
    - name: Build and test
      run: |
        npm run build
        npm run test
        # TODO: publish compiled source as single-file executable
